version: "3"
services:
  database:
    build: database
    restart: always
    volumes:
      - database:/var/lib/postgresql/data:rw
    ports:
      - "4000:5432"
    env_file:
      - .env
    networks:
      - base
networks:
  base: