name: .NET API Tets

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Copy config
      run: echo $DEV_ENV_FILE >> ServerSightAPI/appsettings.json
      shell: bash
      env:
        CONFIG_CONTENT : ${{secrets.ASP_API_CONFIG}}
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
