name: .NET API Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Copy config
      run: | 
        echo ${{secrets.ASP_API_CONFIG}} >> ServerSightAPI/appsettings.json
        echo ${{secrets.ASP_API_CONFIG}} >> ServerSightAPI/appsettings.Development.json
      shell: bash 
    - name: Create required directories
      run: mkdir ServerSightAPI/Resources/
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
